language: python
python:
- '2.6'
- '2.7'
- '3.3'
- '3.4'
- '3.5'
os:
- linux
matrix:
  allow_failures:
    - os: osx
    - python: '2.6'
install:
- pip install .
- if [[ $TRAVIS_PYTHON_VERSION == "2.6" ]]; then pip install unittest2; fi
- pip install coveralls
script:
- coverage run --source=config_finder setup.py test
after_success: coveralls
sudo: false
